name: geometryhints
channels:
  - default
  - pytorch
  - conda-forge
  - nvidia
  - pytorch3d
dependencies:
  - clang=15.0.7
  - llvm-openmp=15.0.7
  - python=3.9.7
  - pytorch=2.0.1
  - torchvision
  - pytorch-cuda=11.7
  - pytorch-lightning=1.5.4 # training utils
  - pytorch3d=0.7.5 # mesh rendering
  - pillow # image op
  - tensorboard # logging
  - matplotlib # plotting
  - pip
  - pip:
    - black==23.1.0
    - isort==5.12.0
    - kornia==0.6.7 # gradients
    - antialiased-cnns # anti aliased resnet
    - efficientnet_pytorch
    - timm # efficent
    - trimesh # mesh loading/storage, and mesh generation
    - transforms3d # for NeuralRecon's arkit
    - einops # batching one liners
    - moviepy # storing videos
    - pyrender # rendering meshes
    - open3d==0.14.1 # mesh fusion
    - scipy # transformations and a few others
    - protobuf<4.21.0 # lighting/tensorboard fix
    - setuptools==59.5.0 # fix for tensorboard
    - https://github.com/JamieWatson683/scikit-image/archive/single_mesh.zip # single mesh exporting for measure.marching_cubes
