name: fmvs
channels:
  - default
  - pytorch
  - conda-forge
  - nvidia
  - pytorch3d
dependencies:
  - python=3.9.19
  - clang=15.0.7
  - llvm-openmp=15.0.7
  - numpy=1.26.4
  - pytorch=2.0.1
  - torchvision
  - pytorch-cuda=11.7
  # - cudatoolkit-dev=11.7  # nvcc
  - lightning=2.0.0
  - pytorch3d # mesh rendering, https://github.com/facebookresearch/pytorch3d/issues/1679
  - pillow # image op
  - tensorboard # logging
  - matplotlib # plotting
  - h5py
  - pip
  - pip:
    - black==23.1.0
    - isort==5.12.0
    - kornia==0.6.7 # gradients
    - antialiased-cnns # anti aliased resnet
    - efficientnet_pytorch
    - timm # efficent
    - trimesh # mesh loading/storage, and mesh generation
    - transforms3d # for NeuralRecon's arkit
    - einops # batching one liners
    - moviepy # storing videos
    - pyrender # rendering meshes
    - open3d==0.14.1 # mesh fusion
    - scipy # transformations and a few others
    - protobuf<4.21.0 # lighting/tensorboard fix
    - setuptools==59.5.0 # fix for tensorboard
    - pytest==7.2.2
    - pytest-cov==2.7.1
    - pytest-timeout==2.1.0
    - pytest-fail-slow==0.3.0
    - loguru==0.7.2
    # - https://github.com/JamieWatson683/scikit-image/archive/single_mesh.zip # single mesh exporting for measure.marching_cubes
    - opencv-python==4.9.0.80
    - ninja==1.11.1.1
    - ray[train]
    - pandas
    - pytoml
    - scikit-image
    - pyqt5
    - dill
    - easydict


python3 eval.py --model fmvs_wrapped --eval_type robustmvd --weights /mnt/nas3/shared/projects/fmvs/fmvs/logs/ray/regression_multids_double_img_encoder_sigmoid_augs/code/_ray_pkg_b38c97c1d7c74197/:/mnt/nas3/shared/projects/fmvs/fmvs/logs/ray/regression_multids_double_img_encoder_sigmoid_augs/TorchTrainer_96783_00000_0_2024-10-07_03-33-27/checkpoint_000017/checkpoint.ckpt --inputs poses intrinsics --max_source_views 7 --kitti_size 336 448 --dtu_size 336 448  --eth3d_size 336 448 --scannet_size 336 448 --tanks_and_temples_size 336 448 --output ./results/kk