[monodepth2]
    root = '/tmp/monodepth2/'

[mvsnet_pl]
    root = '/tmp/mvsnet_pl'

[midas]
    root = '/tmp/midas'

[patchmatchnet]
    root = '/tmp/patchmatchnet'

[cvp_mvsnet]
    root = '/tmp/cvp_mvsnet'

[vis_mvsnet]
    root = '/tmp/vis_mvsnet'

[mvsformerpp]
    root = '/mnt/nas3/shared/projects/fmvs/MVSFormerPlusPlus'

[depthanything]
    root = '/mnt/nas3/shared/projects/fmvs/Depth-Anything-V2'

[mast3r]
    root = '/mnt/nas3/shared/projects/fmvs/mast3r'