!!python/object:doubletake.options.Options
feature_volume_type: simple_cost_volume
batch_size: 16
val_batch_size: 4
cost_volume_aggregation: dot
cv_encoder_type: vit_encoder
depth_decoder_name: dpt.dinov2_vitl14
gpus: 2
image_encoder_name: dinov2_vitl14
matching_num_depth_bins: 96
model_num_views: 6
log_interval: 100
loss_type: log_l1
lr: 0.0001
lr: 0.0001
lr_da_encoder: 0.000001
lr_da_decoder: 0.00001
wd: 0.0001
matching_encoder_type: resnet
name: simplerecon_model
num_sanity_val_steps: 0
num_workers: 12
precision: 16
random_seed: 0
image_width: 512
image_height: 384
val_image_width: 512
val_image_height: 384
matching_scale: 0.25
prediction_scale: 1.0
model_type: depth_model