!!python/object:doubletake.options.Options
feature_volume_type: simple_cost_volume
batch_size: 16
cost_volume_aggregation: dot
cv_encoder_type: cnn_encoder
depth_decoder_name: unet_pp
gpus: 2
image_encoder_name: dinov2_vits14
log_interval: 100
loss_type: log_l1
lr: 0.0001
wd: 0.0001
matching_encoder_type: resnet
name: simplerecon_modelpp_cnnencoder
num_sanity_val_steps: 0
num_workers: 12
precision: 16
random_seed: 0
matching_scale: 0.5
prediction_scale: 0.5714285714285714
image_width: 448
image_height: 336
model_type: depth_model